version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: place-finder-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://place-finder-db:5432/place-finder
      - SPRING_DATASOURCE_USERNAME=evgenii
      - SPRING_DATASOURCE_PASSWORD=08800880
    depends_on:
      - place-finder-db

  place-finder-db:
    image: postgres:latest
    container_name: postgres-placeFinder-db
    volumes:
      - db-placeFinder:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: place-finder
      POSTGRES_USER: evgenii
      POSTGRES_PASSWORD: 08800880


volumes:
  db-placeFinder: